name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on: codebuild-gh-actions-runner-lambda-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo '${{ toJSON(github) }}'
      - run: echo $CUSTOM_SECRET
      - run: echo "::add-mask::$CUSTOM_SECRET"
      - run: echo $CUSTOM_SECRET
      - run: aws sts get-caller-identity
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::290522626011:role/DeploymentRole
          role-session-name: github-actions-${{ github.run_id }}-${{ github.run_attempt }}
      - run: aws s3 ls
      - run: printenv
