name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on: codebuild-CICD-withJohannes-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-7.0-large
    steps:
      - run: echo "Hello World!"
