name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on: codebuild-CICD-withJohannes-${{ github.run_id }}-${{ github.run_attempt }}-aws/codebuild/standard-7.0
    steps:
      - run: echo "Hello World!"
