name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on: codebuild-gh-actions-runner-lambda-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo '${{ toJSON(github) }}'
      - run: echo $CUSTOM_SECRET
      - run: echo "::add-mask::$CUSTOM_SECRET"
      - run: echo $CUSTOM_SECRET
      - run: aws sts get-caller-identity
      # - run: curl $AWS_CONTAINER_CREDENTIALS_FULL_URI
      - run: |
          aws sts assume-role --role-arn arn:aws:iam::290522626011:role/DeploymentRole --role-session-name GitHubActions > assume_role_output.json
          AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' assume_role_output.json) >> $GITHUB_ENV
          AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' assume_role_output.json) >> $GITHUB_ENV
          AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' assume_role_output.json) >> $GITHUB_ENV
          

     # - name: Configure AWS Credentials
     #   uses: aws-actions/configure-aws-credentials@v4
     #   with:
     #     aws-region: eu-central-1
     #     role-to-assume: arn:aws:iam::290522626011:role/DeploymentRole
     #     role-session-name: github-actions-${{ github.run_id }}-${{ github.run_attempt }}
     #     role-chaining: true
      - run: echo ${{ env.Greeting }}
      - run: printenv
      - run: aws s3 ls
      
