name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on: codebuild-gh-actions-runner-lambda-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo '${{ toJSON(github) }}'
      - run: echo $CUSTOM_SECRET
      - run: echo "::add-mask::$CUSTOM_SECRET"
      - run: echo $CUSTOM_SECRET
      - run: printenv
