name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on: codebuild-gh-actions-runner-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-7.0-large
    steps:
      - run: echo '${{ toJSON(github) }}'
      - run: printenv
